// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaProdutos.Data;

#nullable disable

namespace SistemaProdutos.Migrations
{
    [DbContext(typeof(SistemaProdutosDBContext))]
    [Migration("20240512050540_view_movimentos")]
    partial class view_movimentos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("SistemaProdutos.Models.LogMovimentoModel", b =>
                {
                    b.Property<int>("MovId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DataMovimentacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP")
                        .HasDefaultValueSql("current_timestamp");

                    b.Property<int?>("ProdutoId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("TextoMovimento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("MovId");

                    b.HasIndex("ProdutoId");

                    b.ToTable("Log_Movimentos");
                });

            modelBuilder.Entity("SistemaProdutos.Models.MovimentacaoModel", b =>
                {
                    b.Property<int>("AuditId")
                        .HasColumnType("int")
                        .HasColumnName("AuditId");

                    b.Property<DateTime>("DataAlteracao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DataAlteracao");

                    b.Property<int>("DiferencaQuantidade")
                        .HasColumnType("int")
                        .HasColumnName("DiferencaQuantidade");

                    b.Property<int?>("ProdutoId")
                        .HasColumnType("int")
                        .HasColumnName("ProdutoId");

                    b.Property<decimal>("QuantidadeNew")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("QuantidadeNew");

                    b.Property<decimal>("QuantidadeOld")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("QuantidadeOld");

                    b.Property<string>("TextoMovimento")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("TextoMovimento");

                    b.Property<string>("TipoAlteracao")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("TipoAlteracao");

                    b.HasKey("AuditId");

                    b.HasIndex("ProdutoId");

                    b.ToTable((string)null);

                    b.ToView("View_Movimentacoes", (string)null);
                });

            modelBuilder.Entity("SistemaProdutos.Models.ProdutoAuditModel", b =>
                {
                    b.Property<int>("AuditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DataAlteracao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP")
                        .HasDefaultValueSql("current_timestamp");

                    b.Property<string>("Descricao")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("Inativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("Peso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<int?>("ProdutoId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<decimal>("Quantidade")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("TypeAudit")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)");

                    b.Property<decimal>("Valor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.HasKey("AuditId");

                    b.HasIndex("ProdutoId");

                    b.ToTable("Produtos_AUDIT");
                });

            modelBuilder.Entity("SistemaProdutos.Models.ProdutoModel", b =>
                {
                    b.Property<int>("ProdutoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("Inativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("Peso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("Quantidade")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("Valor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.HasKey("ProdutoId");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("SistemaProdutos.Models.LogMovimentoModel", b =>
                {
                    b.HasOne("SistemaProdutos.Models.ProdutoModel", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("SistemaProdutos.Models.MovimentacaoModel", b =>
                {
                    b.HasOne("SistemaProdutos.Models.ProdutoModel", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("SistemaProdutos.Models.ProdutoAuditModel", b =>
                {
                    b.HasOne("SistemaProdutos.Models.ProdutoModel", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produto");
                });
#pragma warning restore 612, 618
        }
    }
}
